name: Deleted Branch

on:
  delete:
    branches: 
    - deletion/*
  workflow_dispatch:

jobs:
  echo:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2

    - name: Echo
      run: |  
        echo "Hello, a deletion action"
